<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXw1WgSs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXw1WgSs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXw1WgSs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXw1WgSs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXw1WgSs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xw1WgSs',
    'container.build_id' => '839ee6e8',
    'container.build_time' => 1631277055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXw1WgSs');
