<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'customer_login' => [[], ['_controller' => 'App\\Controller\\CustomerController::token'], [], [['text', '/customers/']], [], []],
    'customer_create' => [[], ['_controller' => 'App\\Controller\\CustomerController::create'], [], [['text', '/customers/create']], [], []],
    'customer_show' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/customers']], [], []],
    'order_index' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/orders/']], [], []],
    'order_show' => [[], ['_controller' => 'App\\Controller\\OrderController::show'], [], [['text', '/orders/']], [], []],
    'orders_delete' => [['id'], ['_controller' => 'App\\Controller\\OrderController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/orders']], [], []],
    'customer_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/customers/']], [], []],
    'product_create' => [[], ['_controller' => 'App\\Controller\\ProductController::create'], [], [['text', '/customers/create']], [], []],
    'product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/customers']], [], []],
    'product_edit' => [['productd'], ['_controller' => 'App\\Controller\\ProductController::edit'], ['productId' => '\\d+'], [['variable', '/', '[^/]++', 'productd'], ['text', '/customers']], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id'], ['text', '/customers']], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
    'users_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/index']], [], []],
    'users_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/user/login']], [], []],
    'customers_login' => [[], ['_controller' => 'App\\Controller\\CustomerController::token'], [], [['text', '/customer/login']], [], []],
    'customers_index' => [[], ['_controller' => 'App\\Controller\\CustomerController::index'], [], [['text', '/customer/index']], [], []],
    'customers_create' => [[], ['_controller' => 'App\\Controller\\CustomerController::create'], [], [['text', '/customer/create']], [], []],
    'orders_create' => [[], ['_controller' => 'App\\Controller\\OrderController::create'], [], [['text', '/order/create']], [], []],
    'orders_index' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order/index']], [], []],
    'orders_show' => [[], ['_controller' => 'App\\Controller\\OrderController::show'], [], [['text', '/order/show']], [], []],
];
